import type { EntityDef, FieldDef, Option, RefSpec } from "./types";

// =====================================================================
// Master data configuration. Each entry drives one list page and one
// edit form under /sales/admin/<key>. Field names MUST match the column
// names in sales_module_v1.sql. Adding a column: add it in SQL, then add a
// FieldDef here. Never rename a field that already holds data.
// =====================================================================

const opts = (pairs: [string, string][]): Option[] => pairs.map(([value, label]) => ({ value, label }));

const ZONE_ALL = opts([["core", "Core"], ["buffer", "Buffer"], ["all", "All zones"]]);
const ZONE = opts([["core", "Core"], ["buffer", "Buffer"]]);
const SESSION = opts([["morning", "Morning"], ["afternoon", "Afternoon"], ["full_day", "Full day"]]);
const WEEKDAY = opts([["0", "Sunday"], ["1", "Monday"], ["2", "Tuesday"], ["3", "Wednesday"], ["4", "Thursday"], ["5", "Friday"], ["6", "Saturday"]]);
const MEAL = opts([["EP", "EP - room only"], ["CP", "CP - with breakfast"], ["MAP", "MAP - breakfast + one meal"], ["AP", "AP - full board"]]);

// Reusable references
const PARK: RefSpec = { table: "sales_parks", select: "id, name", order: "name", label: ["name"] };
const PROPERTY: RefSpec = { table: "sales_properties", select: "id, name", order: "name", label: ["name"] };
const LOCATION: RefSpec = { table: "sales_locations", select: "id, name, type", order: "name", label: ["name"] };
const ROOM: RefSpec = {
  table: "sales_room_categories",
  select: "id, name, sales_properties(name)",
  order: "name",
  label: ["sales_properties.name", "name"],
};
const SEASON: RefSpec = { table: "sales_seasons", select: "id, name, date_from", order: "date_from", label: ["name", "date_from"] };

const sort: FieldDef = { name: "sort", label: "Sort order", type: "int", empty: 0, help: "Lower numbers appear first." };
const active: FieldDef = { name: "active", label: "Active", type: "bool", initial: true, help: "Inactive items are hidden from the itinerary builder." };
const notes: FieldDef = { name: "notes", label: "Notes", type: "textarea", wide: true };
const taxPct: FieldDef = { name: "tax_pct", label: "Tax %", type: "number", empty: 0 };
const validFrom: FieldDef = { name: "valid_from", label: "Valid from", type: "date", required: true };
const validTo: FieldDef = { name: "valid_to", label: "Valid to", type: "date", required: true };

export const ENTITIES: EntityDef[] = [
  // ------------------------------ Places ------------------------------
  {
    key: "parks",
    table: "sales_parks",
    title: "Parks",
    singular: "park",
    group: "Places",
    icon: "route",
    description: "National parks, with descriptions used in itineraries.",
    fields: [
      { name: "name", label: "Park name", type: "text", required: true, placeholder: "e.g. Tadoba-Andhari Tiger Reserve" },
      { name: "state", label: "State", type: "text", placeholder: "e.g. Maharashtra" },
      { name: "short_desc", label: "Short description", type: "textarea", wide: true, help: "One or two lines for cards and summaries." },
      { name: "long_desc", label: "Long description", type: "textarea", wide: true, help: "Shown in the client itinerary." },
      { name: "season_notes", label: "Season notes", type: "textarea", wide: true, placeholder: "e.g. Core zones open 1 Oct - 30 Jun" },
      sort,
      active,
    ],
    list: ["name", "state", "active"],
    order: [{ column: "sort", ascending: true }, { column: "name", ascending: true }],
    deleteWarning: "Deleting a park also deletes its closures, safari rates and park-specific content.",
  },
  {
    key: "closures",
    table: "sales_park_closures",
    title: "Park closures",
    singular: "closure",
    group: "Places",
    icon: "x",
    description: "Weekly closures (e.g. Tadoba core on Tuesday) and dated closures (Holi, Diwali, monsoon).",
    fields: [
      { name: "park_id", label: "Park", type: "ref", ref: PARK, required: true },
      { name: "closure_type", label: "Type", type: "select", required: true, options: opts([["weekly", "Every week"], ["date_range", "Specific dates"]]), initial: "weekly" },
      { name: "zone", label: "Zone", type: "select", required: true, options: ZONE_ALL, initial: "core" },
      { name: "session", label: "Session closed", type: "select", required: true, options: SESSION, initial: "full_day" },
      { name: "weekday", label: "Day of week", type: "select", options: WEEKDAY, asNumber: true, help: "Only for weekly closures." },
      { name: "date_from", label: "From date", type: "date", help: "Only for specific dates." },
      { name: "date_to", label: "To date", type: "date", help: "Same as From for a single day." },
      { name: "label", label: "Label", type: "text", placeholder: "e.g. Holi, Weekly core closure" },
    ],
    list: ["park_id", "closure_type", "zone", "session", "weekday", "date_from", "date_to", "label"],
    filters: ["park_id"],
    order: [{ column: "closure_type", ascending: false }, { column: "weekday", ascending: true }, { column: "date_from", ascending: true }],
  },
  {
    key: "locations",
    table: "sales_locations",
    title: "Airports, stations & cities",
    singular: "location",
    group: "Places",
    icon: "fileSearch",
    description: "Pick-up and drop points for transfers. Lodges are added here automatically.",
    fields: [
      { name: "type", label: "Type", type: "select", required: true, options: opts([["airport", "Airport"], ["railway", "Railway station"], ["city", "City"], ["other", "Other"]]), initial: "airport" },
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Nagpur Airport" },
      { name: "code", label: "Code", type: "text", placeholder: "e.g. NAG" },
      { name: "state", label: "State", type: "text" },
      active,
    ],
    list: ["name", "type", "code", "state", "active"],
    order: [{ column: "type", ascending: true }, { column: "name", ascending: true }],
    listFilter: { column: "type", op: "neq", value: "property" },
  },

  // ------------------------------ Stay ------------------------------
  {
    key: "properties",
    table: "sales_properties",
    title: "Lodges & hotels",
    singular: "lodge or hotel",
    group: "Stay",
    icon: "building",
    description: "Your lodges, partner lodges and city hotels.",
    afterSave: "property-location",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "kind", label: "Type", type: "select", required: true, options: opts([["own_lodge", "Own lodge"], ["partner_lodge", "Partner lodge"], ["city_hotel", "City hotel"]]), initial: "partner_lodge" },
      { name: "park_id", label: "Park", type: "ref", ref: PARK, help: "Leave empty for city hotels." },
      { name: "city", label: "City", type: "text", help: "For city hotels." },
      { name: "short_desc", label: "Short description", type: "textarea", wide: true },
      { name: "long_desc", label: "Long description", type: "textarea", wide: true, help: "Shown in the client itinerary." },
      { name: "address", label: "Address", type: "textarea", wide: true },
      { name: "lat", label: "Latitude", type: "number" },
      { name: "lng", label: "Longitude", type: "number" },
      { name: "check_in_time", label: "Check-in time", type: "time" },
      { name: "check_out_time", label: "Check-out time", type: "time" },
      { name: "amenities", label: "Amenities", type: "tags", wide: true, placeholder: "Pool, Spa, Library", help: "Separate with commas." },
      { name: "activities", label: "Activities", type: "tags", wide: true, placeholder: "Nature walk, Village visit", help: "Separate with commas." },
      { name: "child_policy", label: "Child policy", type: "textarea", wide: true },
      { name: "fallback_priority", label: "Fallback priority", type: "int", empty: 100, initial: 100, help: "When two lodges are in the same park, the lower number is offered first." },
      { name: "djubo_property_id", label: "Djubo property ID", type: "text", help: "For the availability link later." },
      sort,
      active,
    ],
    list: ["name", "kind", "park_id", "fallback_priority", "active"],
    filters: ["park_id"],
    order: [{ column: "sort", ascending: true }, { column: "name", ascending: true }],
    deleteWarning: "Deleting a lodge also deletes its rooms, rates, seasons, transfer routes and images. Consider marking it inactive instead.",
  },
  {
    key: "rooms",
    table: "sales_room_categories",
    title: "Room categories",
    singular: "room category",
    group: "Stay",
    icon: "clipboard",
    description: "Room types at each lodge and how many people they take.",
    fields: [
      { name: "property_id", label: "Lodge / hotel", type: "ref", ref: PROPERTY, required: true },
      { name: "name", label: "Room name", type: "text", required: true, placeholder: "e.g. AC Cottage" },
      { name: "description", label: "Description", type: "textarea", wide: true },
      { name: "max_adults", label: "Max adults", type: "int", empty: 2, initial: 2 },
      { name: "max_children", label: "Max children", type: "int", empty: 1, initial: 1 },
      { name: "extra_bed", label: "Extra bed possible", type: "bool" },
      { name: "bed_type", label: "Bed type", type: "text", placeholder: "e.g. King or twin" },
      { name: "room_count", label: "Number of rooms", type: "int" },
      { name: "djubo_room_id", label: "Djubo room ID", type: "text" },
      sort,
      active,
    ],
    list: ["property_id", "name", "max_adults", "max_children", "room_count", "active"],
    filters: ["property_id"],
    order: [{ column: "sort", ascending: true }, { column: "name", ascending: true }],
    deleteWarning: "Deleting a room category also deletes its rates.",
  },
  {
    key: "seasons",
    table: "sales_seasons",
    title: "Seasons",
    singular: "season",
    group: "Stay",
    icon: "fileText",
    description: "Named date ranges (peak, festive, low). Optional labels for rates.",
    fields: [
      { name: "property_id", label: "Lodge / hotel", type: "ref", ref: PROPERTY, help: "Leave empty to apply to all." },
      { name: "name", label: "Season name", type: "text", required: true, placeholder: "e.g. Peak 2026-27" },
      { name: "date_from", label: "From", type: "date", required: true },
      { name: "date_to", label: "To", type: "date", required: true },
    ],
    list: ["name", "property_id", "date_from", "date_to"],
    filters: ["property_id"],
    order: [{ column: "date_from", ascending: true }],
  },
  {
    key: "room-rates",
    table: "sales_room_rates",
    title: "Room rates",
    singular: "room rate",
    group: "Stay",
    icon: "barChart",
    description: "Per room per night, by date range and meal plan.",
    fields: [
      { name: "room_category_id", label: "Room", type: "ref", ref: ROOM, required: true },
      { name: "season_id", label: "Season label", type: "ref", ref: SEASON, help: "Optional; the dates below are what the pricing uses." },
      validFrom,
      validTo,
      { name: "meal_plan", label: "Meal plan", type: "select", required: true, options: MEAL, initial: "AP" },
      { name: "rate_double", label: "Double occupancy rate", type: "money", required: true, help: "Per room per night." },
      { name: "rate_single", label: "Single occupancy rate", type: "money" },
      { name: "extra_adult", label: "Extra adult", type: "money" },
      {
        name: "child_rates",
        label: "Child rates",
        type: "json",
        empty: [],
        initial: [],
        wide: true,
        help: 'Age bands per night, e.g. [{"min_age": 5, "max_age": 11, "rate": 2500}]. Leave [] if none.',
      },
      { name: "weekend_days", label: "Weekend days", type: "weekdays", help: "Days that use the weekend rates. Leave all unticked if the rate is the same every day." },
      { name: "weekend_rate_double", label: "Weekend rate (double)", type: "money" },
      { name: "weekend_rate_single", label: "Weekend rate (single)", type: "money" },
      { name: "min_nights", label: "Minimum nights", type: "int", empty: 1, initial: 1 },
      taxPct,
      { name: "rates_include_tax", label: "Rates include tax", type: "bool", initial: true },
      { name: "cost_double", label: "Net cost (double)", type: "money", help: "Internal only. Never shown to guests." },
      {
        name: "compulsory_supplement",
        label: "Compulsory supplement",
        type: "json",
        wide: true,
        help: 'Optional, e.g. {"label": "Gala dinner", "date": "2027-12-31", "per_person": 8000}',
      },
      notes,
      active,
    ],
    list: ["room_category_id", "valid_from", "valid_to", "meal_plan", "rate_double", "weekend_rate_double", "active"],
    filters: ["room_category_id"],
    order: [{ column: "valid_from", ascending: true }],
  },

  // ------------------------- Safaris & travel -------------------------
  {
    key: "safari-rates",
    table: "sales_safari_rates",
    title: "Safari rates",
    singular: "safari rate",
    group: "Safaris & travel",
    icon: "route",
    description: "Per jeep or per seat, by park, zone, session and date range.",
    fields: [
      { name: "park_id", label: "Park", type: "ref", ref: PARK, required: true },
      { name: "zone", label: "Zone", type: "select", required: true, options: ZONE, initial: "core" },
      { name: "session", label: "Session", type: "select", required: true, options: SESSION, initial: "morning" },
      { name: "vehicle_type", label: "Vehicle", type: "select", required: true, initial: "exclusive_jeep", options: opts([["exclusive_jeep", "Exclusive jeep"], ["shared_jeep", "Shared jeep"], ["canter", "Canter"], ["other", "Other"]]) },
      { name: "pricing_unit", label: "Priced", type: "select", required: true, initial: "per_vehicle", options: opts([["per_vehicle", "Per vehicle"], ["per_seat", "Per seat"]]) },
      { name: "nationality", label: "Applies to", type: "select", required: true, initial: "all", options: opts([["all", "All guests"], ["indian", "Indian guests"], ["foreign", "Foreign guests"]]) },
      validFrom,
      validTo,
      { name: "weekday_rate", label: "Weekday rate", type: "money", required: true },
      { name: "weekend_rate", label: "Weekend rate", type: "money" },
      { name: "weekend_days", label: "Weekend days", type: "weekdays" },
      { name: "max_pax", label: "Max guests per vehicle", type: "int", empty: 6, initial: 6 },
      { name: "includes_naturalist", label: "Naturalist included", type: "bool", initial: true },
      { name: "naturalist_fee", label: "Naturalist fee", type: "money", empty: 0 },
      { name: "guide_fee", label: "Guide fee", type: "money", empty: 0 },
      taxPct,
      notes,
      active,
    ],
    list: ["park_id", "zone", "session", "vehicle_type", "valid_from", "valid_to", "weekday_rate", "weekend_rate", "active"],
    filters: ["park_id"],
    order: [{ column: "valid_from", ascending: true }],
  },
  {
    key: "transfers",
    table: "sales_transfer_rates",
    title: "Transfer rates",
    singular: "transfer rate",
    group: "Safaris & travel",
    icon: "route",
    description: "One-way vehicle rates between airports, stations, cities and lodges.",
    fields: [
      { name: "from_location_id", label: "From", type: "ref", ref: LOCATION, required: true },
      { name: "to_location_id", label: "To", type: "ref", ref: LOCATION, required: true },
      { name: "vehicle_type", label: "Vehicle", type: "text", required: true, placeholder: "e.g. Toyota Innova Crysta" },
      { name: "capacity", label: "Capacity (guests)", type: "int", empty: 4, initial: 4 },
      { name: "rate", label: "Rate (one way)", type: "money", required: true },
      { name: "distance_km", label: "Distance (km)", type: "number" },
      { name: "drive_hours", label: "Drive time (hours)", type: "number" },
      { name: "night_surcharge", label: "Night surcharge", type: "money", empty: 0 },
      { name: "valid_from", label: "Valid from", type: "date", help: "Optional." },
      { name: "valid_to", label: "Valid to", type: "date", help: "Optional." },
      { name: "bidirectional", label: "Same rate for the return trip", type: "bool", initial: true },
      taxPct,
      notes,
      active,
    ],
    list: ["from_location_id", "to_location_id", "vehicle_type", "capacity", "rate", "drive_hours", "bidirectional", "active"],
    filters: ["from_location_id", "to_location_id"],
    order: [{ column: "rate", ascending: true }],
  },
  {
    key: "addons",
    table: "sales_addons",
    title: "Add-ons & activities",
    singular: "add-on",
    group: "Safaris & travel",
    icon: "clipboard",
    description: "Extras such as village visits, city tours or spa treatments.",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", wide: true },
      { name: "property_id", label: "Lodge / hotel", type: "ref", ref: PROPERTY, help: "Optional." },
      { name: "park_id", label: "Park", type: "ref", ref: PARK, help: "Optional." },
      { name: "pricing_unit", label: "Priced", type: "select", required: true, initial: "per_person", options: opts([["per_person", "Per person"], ["per_group", "Per group"], ["per_vehicle", "Per vehicle"], ["per_room", "Per room"]]) },
      { name: "rate", label: "Rate", type: "money", required: true },
      taxPct,
      active,
    ],
    list: ["name", "property_id", "park_id", "pricing_unit", "rate", "active"],
    order: [{ column: "name", ascending: true }],
  },

  // ---------------------------- Commercial ----------------------------
  {
    key: "offers",
    table: "sales_offers",
    title: "Offers",
    singular: "offer",
    group: "Commercial",
    icon: "barChart",
    description: "Early bird rates, percentage discounts and stay-X-pay-Y deals.",
    fields: [
      { name: "name", label: "Offer name", type: "text", required: true, placeholder: "e.g. Early Bird 2026-27" },
      { name: "offer_type", label: "Type", type: "select", required: true, initial: "percent", options: opts([["percent", "Percentage off"], ["fixed_rate", "Fixed room rate"], ["stay_pay", "Stay X nights, pay Y"]]) },
      { name: "value", label: "Value", type: "number", help: "Percent off, or the new per-room-per-night rate for a fixed rate offer." },
      { name: "stay_nights", label: "Stay nights", type: "int", help: "Stay X pay Y only." },
      { name: "pay_nights", label: "Pay nights", type: "int", help: "Stay X pay Y only." },
      { name: "applies_to", label: "Applies to", type: "multiselect", empty: ["room"], initial: ["room"], options: opts([["room", "Rooms"], ["safari", "Safaris"], ["transfer", "Transfers"], ["addon", "Add-ons"]]) },
      { name: "property_ids", label: "Lodges", type: "refs", ref: PROPERTY, empty: [], help: "Tick none for all lodges." },
      { name: "room_category_ids", label: "Rooms", type: "refs", ref: ROOM, empty: [], help: "Tick none for all rooms. Needed for fixed rate offers." },
      { name: "book_from", label: "Book from", type: "date" },
      { name: "book_to", label: "Book until", type: "date" },
      { name: "travel_from", label: "Travel from", type: "date" },
      { name: "travel_to", label: "Travel until", type: "date" },
      { name: "min_nights", label: "Minimum nights", type: "int", empty: 1, initial: 1 },
      { name: "combinable", label: "Can combine with other offers", type: "bool" },
      active,
    ],
    list: ["name", "offer_type", "value", "travel_from", "travel_to", "active"],
    order: [{ column: "name", ascending: true }],
  },

  // ------------------------------ Content ------------------------------
  {
    key: "content",
    table: "sales_content_blocks",
    title: "Content library",
    singular: "content block",
    group: "Content",
    icon: "fileText",
    description: "Day templates, inclusions, exclusions, notes and terms used in itineraries.",
    fields: [
      {
        name: "kind",
        label: "Kind",
        type: "select",
        required: true,
        initial: "day_safari",
        options: opts([
          ["day_arrival", "Day template - arrival"],
          ["day_safari", "Day template - safari day"],
          ["day_transfer", "Day template - transfer day"],
          ["day_leisure", "Day template - leisure day"],
          ["day_departure", "Day template - departure"],
          ["inclusions", "Inclusions"],
          ["exclusions", "Exclusions"],
          ["important_notes", "Important notes"],
          ["payment_terms", "Payment terms"],
          ["cancellation_terms", "Cancellation terms"],
          ["about_trip", "About the trip"],
          ["other", "Other"],
        ]),
      },
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "body",
        label: "Text",
        type: "textarea",
        required: true,
        wide: true,
        help: "Placeholders: {lodge} {park} {from} {to} {hours}. For lists, put one item per line.",
      },
      { name: "park_id", label: "Park", type: "ref", ref: PARK, help: "Optional: use only for this park." },
      { name: "property_id", label: "Lodge / hotel", type: "ref", ref: PROPERTY, help: "Optional: use only for this lodge." },
      { name: "is_default", label: "Default for this kind", type: "bool" },
      sort,
      active,
    ],
    list: ["kind", "title", "park_id", "property_id", "is_default", "active"],
    filters: ["kind"],
    order: [{ column: "kind", ascending: true }, { column: "sort", ascending: true }],
  },
  {
    key: "reasons",
    table: "sales_reasons",
    title: "Lost & cancel reasons",
    singular: "reason",
    group: "Content",
    icon: "x",
    description: "Dropdown choices when a query is marked lost or cancelled.",
    fields: [
      { name: "kind", label: "Used when", type: "select", required: true, initial: "lost", options: opts([["lost", "Marking lost"], ["cancelled", "Marking cancelled"]]) },
      { name: "label", label: "Reason", type: "text", required: true },
      sort,
      active,
    ],
    list: ["kind", "label", "sort", "active"],
    filters: ["kind"],
    order: [{ column: "kind", ascending: true }, { column: "sort", ascending: true }],
  },
];

export const ENTITY_GROUPS = ["Places", "Stay", "Safaris & travel", "Commercial", "Content"];

export function getEntity(key: string) {
  return ENTITIES.find((e) => e.key === key) ?? null;
}
